3 adding aws sdk
ESELdevelopment/ecmanager pull request #14
Opened 2024-08-27 12:08 UTC by Marcel2603

2024-08-27 12:08 UTC, Marcel2603 commented
dependes on #9

2024-09-15 15:19 UTC, tzabbi commented
Do we want to add WIP or draft, when the PR is not ready to merge?

2024-09-15 16:20 UTC, Marcel2603 commented
Its already marked as draft

2024-09-16 15:16 UTC, tzabbi commented
ahh yes sorry, I looked at the wrong place -.-

2024-09-17 21:34 UTC, Marcel2603 commented
# How to review
- Read the Readme
- Start moto
- create a cluster
- After that start the aws-main-Gofile (with MotoConnection)
- it should print all clusters

- View the code
- View the tests. If you dont like the tests, pls go ahead and modify them. Ive followed this guide https://dev.to/aws-builders/testing-with-aws-sdk-for-go-v2-without-interface-mocks-55de
  - Its great, because you dont need ugly mocks

2024-09-17 21:35 UTC, Marcel2603 commented
resolve #3

2024-09-25 12:34 UTC, tzabbi requested changes
Go code looks valid for me.

2024-09-25 12:34 UTC, tzabbi commented on README.md
> +```
We have this in line 14-16 too, why?

2024-09-25 12:34 UTC, tzabbi commented on README.md
> +```bash
we have to add the following env var: `export AWS_DEFAULT_REGION='us-east-1'`

Otherwise aws cli does not work:

```bash
$ aws --endpoint-url=http://localhost:5000 ecs create-cluster --cluster-name test-cluster
> You must specify a region. You can also configure your region by running "aws configure".
``

2024-09-25 12:34 UTC, tzabbi commented on README.md
> +aws --endpoint-url=http://localhost:5000 ecs ...
You can remove the `--endpoint-url=http://localhost:5000` since we define the environment variable `export AWS_ENDPOINT_URL=http://localhost:5000`

2024-09-25 12:34 UTC, tzabbi commented on internal/aws/ecs.go
> +func (*resolverV2) ResolveEndpoint(ctx context.Context, params ecs.EndpointParameters) (
we should add a a var character in method declartion `(r *resolverV2)`.

2024-09-25 12:34 UTC, tzabbi commented on cmd/aws/main.go
> +import (
Can we use two spaces for a tab instead of four spaces?

2024-09-25 14:26 UTC, Marcel2603 commented on README.md
> +```bash
good point. I fix that

2024-09-25 14:29 UTC, Marcel2603 commented on README.md
> +aws --endpoint-url=http://localhost:5000 ecs ...
hmmm i would like to have the explizit command, because this section of the readme deals with moto and is not in the context of the localdev

2024-09-25 14:53 UTC, Marcel2603 commented on cmd/aws/main.go
> +import (
done

2024-09-25 14:53 UTC, Marcel2603 commented on internal/aws/ecs.go
> +func (*resolverV2) ResolveEndpoint(ctx context.Context, params ecs.EndpointParameters) (
done

2024-09-28 11:48 UTC, tzabbi approved these changes

2024-09-28 11:49 UTC, merged

2024-09-28 11:49 UTC, tzabbi commented
# Review
* Looks good to me